import csv
from faker import Faker
from faker.providers import BaseProvider

EXTRA_SPACE = ['', ' ']

class ChapterProvider(BaseProvider):
    CHAPTER_NAMES = [
        'Achensee',
        'Achental',
        'Bad Aibling',
        'Aichach',
        'Akademische Sektion München',
        'Allgäu-Immenstadt',
        'Allgäu-Kempten',
        'Alpenkranzl Erding',
        'Alpenkranzl Holzkirchen',
        'Alpenland',
        'Alpiner Ski-Club e.V. Mü.',
        'Amberg',
        'Ammersee',
        'Ansbach',
        'Pfaffenhofen-Asch',
        'Aschaffenburg',
        'Augsburg',
        'Bamberg',
        'Bayerland',
        'Bayreuth',
        'Berchtesgaden',
        'Bergbund',
        'Bergbund Rosenheim',
        'Bergfried',
        'Alpenklub Berggeist',
        'Bergland',
        'Bodenschneid',
        'Burghausen',
        'Burgkirchen',
        'Coburg',
        'Deggendorf',
        'Deut. Skiclub Nürnberg',
        'Dillingen',
        'Donauwörth',
        'Ebersberg-Grafing',
        'Edelweiß München',
        'Eger und Egerland',
        'Eggenfelden',
        'Eichstätt-Neuburg',
        'Erlangen',
        'Firnland',
        'Forchheim',
        'Frankenland',
        'Freilassing',
        'Freising',
        'Fürth',
        'Füssen',
        'Gangkofen',
        'Garmisch-Partenkirchen',
        'Geltendorf',
        'Gersthofen',
        'Gipfelstürmer 08',
        'Gleißental',
        'Greiz Sitz Marktredw.',
        'Bad Griesbach i.Rottal',
        'Günzburg',
        'Gunzenhausen',
        'Haag',
        'Hersbruck',
        'Hesselberg',
        'Hochland',
        'Hof',
        'Illertissen',
        'Ingolstadt',
        'Isartal',
        'Kampenwand',
        'Karlsbad',
        'Kaufbeuren-Gablonz',
        'Kelheim',
        'Bad Kissingen',
        'Königsberg',
        'Krumbach',
        'Kulmbach',
        'Landsberg',
        'Landshut',
        'Lauf a.d.P.',
        'Laufen',
        'Schongau',
        'Leitzachtal',
        'Lenggries',
        'Lichtenfels',
        'Lindau',
        'Männer Turnver. Mchn.',
        'Mainburg',
        'Memmingen',
        'Mering',
        'Miesbach',
        'Mindelheim',
        'Mittelfranken',
        'Mittenwald',
        'Moosburg',
        'Mühldorf',
        'München',
        'Murnau',
        'Neuland',
        'Neumarkt/Oberpfalz',
        'Neuötting-Altötting',
        'Neustadt/Coburg',
        'Neu-Ulm',
        'Nördlingen',
        'Noris',
        'Nürnberg',
        'Oberland',
        'Oberstaufen-Lindenberg',
        'Oberstdorf',
        'Passau',
        'Peißenberg',
        'Peiting',
        'Pfarrkirchen',
        'Pfronten',
        'Dinkelsbühl',
        'Prien am Chiemsee',
        'Regensburg',
        'Bad Reichenhall',
        'Ringsee',
        'Röthenbach',
        'Rosenheim',
        'Main-Spessart',
        'Rothenburg o.d.T.',
        'Se. Rottal Neumarkt-St. Veit',
        'Schliersee',
        'Schrobenhausen',
        'Schwabach',
        'Schwabmünchen',
        'Schweinfurt',
        'Selb',
        'Simbach/Inn',
        'Starnberg',
        'Straubing',
        'Sulzbach-Rosenberg',
        'Tegernsee',
        'Teisendorf',
        'Tittmoning',
        'Tölz',
        'Traunstein',
        'Treuchtlingen',
        'Trostberg',
        'Turner-Alpenkränzchen',
        'Tutzing',
        'Univ. Sportclub Mü.',
        'Vierseenland',
        'Waakirchen',
        'Wasserburg am Inn',
        'Weiden',
        'Weiler',
        'Weilheim',
        'Weißenburg',
        'Wolfratshausen',
        'Würzburg',
        'Friedberg',
        'Taufkirchen/Vils',
        'Zorneding',
        'Otterfing',
        'Wildsteig',
        'Bergbund Hausham',
        'Garching',
        'Karpaten',
        'Bergfreunde München',
        'Oy/Allgäu',
        'Kronach/Frankenwald',
        'Abenberg',
        'Georgensgmünd',
        'Feucht',
        'Altdorf',
        'Dingolfing',
        'Roth',
        'Feuchtwangen',
        'Kaufering',
        'Bergbund Würzburg',
        'Herrieden',
        'Alpen.Net',
        'Haar',
        'Gay Outdoor Club',
        'Markt Schwaben',
        'Lechbruck',
        'Aischtal',
        'Alpinistenclub',
        'Stützpunkt Inntal',
        'Gipfelkreuz',
        'Gay Alpin München',
    ]

    def chapter(self) -> str:
        return self.random_element(self.CHAPTER_NAMES) + self.random_element(EXTRA_SPACE)
    
class BadgeProvider(BaseProvider):
    BADGE_STATUS = ['J', 'j', 'B', 'b', 'N', 'n', '']

    def badge(self) -> str:
        return self.random_element(self.BADGE_STATUS) + self.random_element(EXTRA_SPACE)

# output csv file
OUTPUT_FILE = 'JLMarken Test.csv'

# header with column names for the csv file
HEADER = ['Vorname', 'Nachname', 'Sektion', 'JM2023']

# setup faker with custom providers for chapters and badge status
fake = Faker('de_DE')
fake.add_provider(ChapterProvider)
fake.add_provider(BadgeProvider)

with open(OUTPUT_FILE, 'w', encoding='cp1252') as file:
    writer = csv.writer(file, delimiter=';')

    # write header
    writer.writerow(HEADER)

    # write 1000 fake entries
    for _ in range(1000):
        writer.writerow([fake.first_name(), fake.last_name(), fake.chapter(), fake.badge()])
